### ISSUE TITLE
Docs: Feedback for SQL Basics on Hazelcast Cloud (Stock Ticker)

### ISSUE THREAD

**Issue by myawnhc** [hazelcast-guides/sql_stock_ticker_cloud#6]
Hi, I have some feedback about [this page](https://github.com/hazelcast-guides/sql_stock_ticker_cloud/edit/master/docs/modules/ROOT/pages/sql_stock_ticker_cloud.adoc)

In step 1, item 3, we create a mapping with a field named 'amt'. 
In step 2, in all 3 items, we reference this same item (I believe) but call it 'amount', resulting in an error

myawn-udemy SQL> SELECT ticker AS Symbol, ROUND(price,2) AS Price, amount AS "Shares Sold"
 ... FROM trades_topic;
 ERROR From line 1, column 51 to line 1, column 56: Column 'amount' not found in any table

I didn't edit the page directly as I'm not sure if you'd rather go with 'amt' or 'amount' as the name.

**Comment by srknzl** [comment]
Indeed the following patch seems to be necessary 
![image](https://github.com/hazelcast-guides/sql_stock_ticker_cloud/assets/32355782/75c17b01-2915-4188-bd59-f6711fdd795c)

**Comment by srknzl** [comment]
there is another similar(due to amt vs amount) defect in Step6.1, in SQL statement: 

```sql
CREATE OR REPLACE VIEW tro_enriched AS
     SELECT
          tro.ticker AS ticker,
          companies.company as company,
          ROUND(tro.price,2) AS price,
          tro.amount AS shares,
          tro.trade_ts
     FROM trades_ordered AS tro
     JOIN companies
     ON companies.ticker = tro.ticker;
```

**Comment by srknzl** [comment]
(The following seems like not related to amt vs amount. )

Also 

```sql
SELECT * FROM high_low_enriched
     WHERE ticker = "APPL";
```

on step 6.3 fails with

" ERROR From line 1, column 48 to line 1, column 53: Column 'APPL' not found in any table" for me 


**EDIT: Changing to single quotes works** i.e `SELECT * FROM high_low_enriched WHERE ticker = 'APPL';`
